services:
  - type: web
    name: aitoolmate
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: WHATSAPP_API_SID
        sync: false
      - key: WHATSAPP_API_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER
        sync: false
      - key: GOOGLE_CLOUD_PROJECT_ID
        sync: false
      - key: BIGQUERY_DATASET
        sync: false
      - key: BIGQUERY_TABLE
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
